platform :android do
  desc "Distribute APK to Firebase"
    lane :distribute_to_firebase do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mezoattalla123@gmail.com",
      release_notes: "New version released via Fastlane"
    )
  end
end