import 'package:flutter/material.dart';

abstract class AppColors {
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color backgroundBlack = Color(0xFF242424);
  static const Color backgroundWhite = Color(0xFFFFFFFF);
  static const Color body = Color(0xFF757575);
  static const Color grey100 = Color(0xFF242424);
  static const Color grey90 = Color(0xFF404040);
  static const Color grey80 = Color(0xFF616161);
  static const Color grey70 = Color(0xFF757575);
  static const Color grey60 = Color(0xFF9E9E9E);
  static const Color grey50 = Color(0xFFC2C2C2);
  static const Color grey40 = Color(0xFFE0E0E0);
  static const Color grey30 = Color(0xFFEDEDED);
  static const Color grey20 = Color(0xFFF5F5F5);
  static const Color primary100 = Color(0xFF247CFF);
  static const Color primary80 = Color(0xFF5096FF);
  static const Color primary60 = Color(0xFF7CB0FF);
  static const Color primary40 = Color(0xFFD3E5FF);
  static const Color primary20 = Color(0xFFEAF2FF);
  static const Color primarySurface = Color(0xFFF4F8FF);
  static const Color secondarySurfaceBlue = Color(0xFFEAF2FF);
  static const Color secondarySurfaceGreen = Color(0xFFE9FAEF);
  static const Color secondarySurfaceRed = Color(0xFFFFEEEF);
  static const Color secondaryFillBlue = Color(0xFF247CFF);
  static const Color secondaryFillGreen = Color(0xFF22C55E);
  static const Color secondaryFillRed = Color(0xFFFF4C5E);
  static const Color secondarySurfaceText = Color(0xFFFAFAFB);
  static const Color secondaryForm = Color(0xFFFDFDFF);
  static const Color secondaryChat = Color(0xFFF8F9FD);
  static const Color warning100 = Color(0xFFFFD600);
  static const Color warning80 = Color(0xFFFFDD2A);
  static const Color warning60 = Color(0xFFFFE455);
  static const Color warning40 = Color(0xFFFFEA80);
  static const Color warning20 = Color(0xFFFFF1AA);
  static const Color warningSurface = Color(0xFFFFF7CC);
  static const Color transparent = Colors.transparent;
}
